### ISSUE TITLE
Don't you Tailwind.

### ISSUE THREAD

**Issue by ratnesh24** [anilsangwa/react-redux-boilerplate#1]
Hello,
Please use a good UI framework like Ant. design or any other.
Tailwind, create a mess in coding

Thank you

**Comment by anilsangwa** [comment]
I agree that tailwind creates a mess, but also it boost development. 
Why I prefer tailwind is because 
- I found much better than bootstrap 
- it helps creating beautiful ui for developers who are not expert in creating css/less/scss from scratch.
Also I prefer ANT design but this was a basic boilerplate so I skipped that.
will add that in later commits.

Thanks for pointing out. I appreciate your time involved in code review.
